using Classe;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ClassLibrary1
{
    public partial class Manager
    {
        public ReadOnlyCollection<Valorant> Valorants { get; set; }
        public IReadOnlyCollection<Bundle> Bundles { get; set; }
        public IReadOnlyCollection<Arme> Armes { get; set; }
        public IReadOnlyCollection<Carte> Cartes { get; set; }

        List<Valorant> valorant = new List<Valorant>();
        List<Bundle> bundles = new List<Bundle>();
        List<Arme> armes = new List<Arme>();
        List<Carte> carte = new List<Carte>();

        public Manager()
        {
            Valorants = new ReadOnlyCollection<Valorant>(valorant);
            Bundles = new ReadOnlyCollection<Bundle>(bundles);
            Armes = new ReadOnlyCollection<Arme>(armes);
            Cartes = new ReadOnlyCollection<Carte>(carte);
        }
        public void ChargeValorant()
        {
            valorant.AddRange(new Valorant[]
            {
                new Valorant("Jett", "Duelist", new ListeAg(), "Coréenne", new Ultime(7, "Jett s’équipe de 7 couteaux de lancer. TIREZ pour lancer un couteau sur une trajectoire droite et précise. Jett récupère tous ses couteaux chaque fois qu’elle tue un adversaire avec l’un d’eux.", "Tempête de Lames","/VideoSpell/Jett/JX.png"), new Signature(0, 1, 0.0, "Jett se propulse dans la direction souhaitée", 2, "Eliminations", "Vent arrière","/VideoSpell/Jett/JE.png"), new Capacite(150, 2, 0.6, "Jett se propulse instantanément dans les airs.", "Courant ascendant","/VideoSpell/Jett/JA.png"), new Capacite(200, 2, 4.5,"Lance une fumigène qui se déclanche au contact d'une surface", "Cloud Burst","/VideoSpell/Jett/JC.png"), new Passif("Drift est une abilité qui permet à Jett de planer lorsque qu'elle saute d'une grande hauteur.", "Drift"),"VideoSpell/Jett/jett.jpg","/VideoSpell/Jett/coree.jpg","Représentante de sa patrie, la Corée du Sud, Jett dispose d'un style de combat basé sur l'agilité et l'esquive, qui lui permet de prendre des risques qu'elle seule peut se permettre de prendre. Elle tourne autour des affrontements et découpe ses ennemis avant même qu'ils ne s'en rendent compte."),
                new Valorant("Phoenix","Dueslist",new ListeAg(), "United Kingdom",new Ultime(6, "Phoenix place une marque au sol. Si Phoenix meurt ou que la durée de la capacité expire, Phoenix réapparaît sur la marque avec tous ses points de vie.", "Revanche", "/PhoX.png"),new Signature(0,1,3.25, "Phoenix s’équipe d’une boule de feu. TIREZ pour lancer la boule de feu qui explose en touchant le sol, créant une zone enflammée qui blesse les unités qui se tiennent dessus.",2,"Kills", "Mains Brûlantes", "/PhoE.png"),new Capacite(250,2,0.7, "Phoenix s’équipe d’un orbe qui explose peut après avoir été lancé, aveuglant les unités qui le regardaient. TIREZ pour que le tir de l’orbe décrive une courbe vers la gauche. TIR ALTERNATIF pour que l’orbe décrive une courbe vers la droite.", "Balle Courbe", "/PhoA.png"),new Capacite(200,1,8, "Phoenix s’équipe d’un mur de feu. TIREZ pour créer une ligne de flamme créant un mur de feu bloquant la vision des joueurs et blessant les adversaires et alliés qui passent à travers. MAINTENEZ votre tir pour légèrement dévier la trajectoire du mur vers votre viseur.", "Brasier", "/PhoC.png"),new Passif("null","null"), "/VideoSpell/Phoenix/pho.jpg", "/VideoSpell/Phoenix/RU.jpg", "En provenance du Royaume-Uni, Phoenix illumine le champ de bataille avec ses pouvoirs astraux et son style de combat flamboyant. Peu importe que les renforts arrivent ou non, il fonce au combat quand il le décide."),
                new Valorant("Yoru","Duelist",new ListeAg(),"Japan",new Ultime(7, "EQUIPEZ-vous d’un masque qui permet de voir entre les dimensions.", "Transfert Dimensionnel", "/VideoSpell/Yoru/YX.png"),new Signature(200,2,30, "EQUIPEZ-vous d’une balise dimensionnelle.TIREZ pour envoyer la balise vers l’avant.UTILISEZ le tir secondaire pour poser la balise devant vous.Activez la balise pour vous y téléporter.UTILISEZ la balise pour feindre la téléportation.",2,"Kill", "Visite Surprise", "/VideoSpell/Yoru/YE.pn"),new Capacite(250,2,0.6, "EQUIPEZ-vous d’un fragment dimensionnel instable arraché à la réalité.TIREZ pour lancer le fragment, qui provoquera un éclat aveuglant peu après avoir touché une surface dure.", "Angle Mort", "/VideoSpell/Yoru/YA.png"),new Capacite(100,1,10, "TIREZ pour activer instantanément le double et l’envoyer vers l’avant. Utilisez le TIR SECONDAIRE pour poser un écho inactif devant vous sans l’activer.", "Feinte ", "/VideoSpell/Yoru/YC.png"),new Passif("Null","Null"), "/VideoSpell/Yoru/yoru.png", "/VideoSpell/Yoru/japon.jpg", "/VideoSpell/Yoru/japon.jpg"),
                new Valorant("Neon","Duelist",new ListeAg(), "Philippines",new Ultime(7, "Libérez toute la puissance et la vitesse de Néon pendant un court instant. TIREZ pour canaliser son pouvoir en un rayon électrique mortel dont la précision reste élevée même en mouvement. La durée et la glissade se réinitialisent à chaque élimination.", "Ultra Vitesse","/Neon_X-Overdrive.png"),new Signature(0,1,10, "Chargez INSTANTANÉMENT le pouvoir de Néon pour décupler sa vitesse. À la fin du chargement, utilisez le TIR SECONDAIRE pour faire une glissade électrique. Vous regagnez une charge de glissade toutes les deux éliminations.",2,"Kills", "Vitesse supérieure", "/Neon_E-High_Gear.png"),new Capacite(200,2,1.1, "Lancez INSTANTANÉMENT un éclair d’énergie qui rebondit une fois. Chaque fois qu’il rencontre une surface, l’éclair électrifie le sol en dessous avec une explosion désorientante.", "Éclair relais", "/Neon_Q-Relay_Bolt.png"),new Capacite(300,1,6, "TIREZ deux lignes d’énergie dans le sol devant vous. Après avoir parcouru une courte distance ou touché une surface, elles créent des murs d’électricité statique qui bloquent la vision et blessent les ennemis qui les traversent.", "Voie Rapide", "/Neon_C-Fast_Lane.png"),new Passif("Utiliser les capacités de neon consomme de l'énergie. Tuer un agent ennemi recharge instantanément l'énergie.","Energie"), "VideoSpell/Neon/neon.jpg", "/VideoSpell/Neon/philipine.jpg", " L'agent philippin, Neon, s'élance vers l'avant à une vitesse fulgurante, libérant de grosses décharges de radiance biomagnétique générées frénétiquement par son corps. Elle se lance à la poursuite des ennemis qui n'ont pas le temps de s'y préparer et les élimine aussi vite que l'éclair."),
                new Valorant("Raze","Duelist",new ListeAg(),"Brazil",new Ultime(8, "Raze s’équipe d’un lance-roquette. TIREZ pour lancer une roquette qui explose dès qu’elle rentre en contact avec un joueur ou un obstacle, créant une grande déflagration qui blesse les joueurs alentours.", "Bouquet final", "/RX.png"),new Signature(0,1,3, "Raze s’équipe d’une grenade à fragmentation. TIREZ pour jeter la grenade qui explose en faisant des dégâts autour d’elle, avant de se diviser en plus petites grenades qui explosent à leur tour autour de l’explosion initiale.",2,"Kills", "Grenade Gigogne","/RE.png"),new Capacite(200,2,5, "Raze jette instantanément un dispositif qui s’accroche à la première surface touchée. RÉUTILISEZ la capacité après qu’elle ait été déployée pour la faire exploser, blessant et propulsant tous les joueurs à portée. Raze et ses alliés ne subissent pas de dégâts du Pack Explosif et peuvent l’utiliser afin de se propulser dans les airs.", "Pack explosif", "/RA.png"),new Capacite(300,1,10, "Raze s’équipe d’un robot explosif. TIREZ pour placer au sol un robot qui avance en ligne droite et rebondit contre les murs. Il explose et occasionne de gros dégâts s’il détecte un adversaire devant lui.", "Boum Bot", "/RC.png"),new Passif("Null", "Null"), "/VideoSpell/Raze/raze.jpg", "/VideoSpell/Raze/bresil.jpg", "Armée de sa personnalité et de sa grosse artillerie, Raze fait une entrée explosive depuis le Brésil. Grâce à sa force brute, elle excelle à débusquer les ennemis retranchés et à faire le ménage dans les espaces étroits, le tout avec une bonne dose de « boum »"),
                new Valorant("Reyna","Duelist",new ListeAg(), "Mexico",new Ultime(6, "Entrez INSTANTANÉMENT en furie, ce qui augmente considérablement vos vitesses de tir, de chargement d’arme et de rechargement. Vous gagnez une infinité de charges pour les compétences se servant de Récolte des âmes. Réussir une élimination réinitialise la durée.", "Impératrice", "/TX_Reyna_X.png"),new Signature(200,2,2, "Vous consommez INSTANTANÉMENT un orbe d’âme proche et devenez intangible pendant un court instant. Si IMPÉRATRICE est active, vous devenez également invisible.",0,"Null", "Rebuffade", "/TX_Reyna_E.png"),new Capacite(200,2,3, "Récolte des âmes : les ennemis tués par Reyna laissent des orbes d’âme qui durent 3  sec. Dévoration : vous consommez INSTANTANÉMENT un orbe d’âme proche pour rapidement regagner des PV pendant un court instant. Au-delà de 100 PV, les PV ainsi gagnés sont perdus progressivement. Si IMPÉRATRICE est active, cette compétence se lancera automatiquement et ne consommera pas d’orbe d’âme.", "Dévoration", "/TX_Reyna_Q.png"),new Capacite(250,2,2, "Compétence Signature – 2 Utilisation possible par tour.ÉQUIPEZ - vous d’un œil éthéré destrucible.ACTIVEZ pour lancer l’oeil vers l’avant sur une courte distance.L’œil rend myope tous les ennemis qui le regardent.", "Œillade", "/TX_Reyna_C.png"),new Passif("Récolte d'âme", "Les ennemis qui meurent de Reyna, ou meurent dans les 3 secondes après avoir subi des dégâts de Reyna, laissent derrière eux des orbes d'âme qui durent 3 secondes."), "VideoSpell/Reyna/reyna.jpg", "/VideoSpell/Reyna/mexique.jpg", " Originaire du cœur du Mexique, Reyna est une experte des combats singuliers qui se renforce à chaque élimination qu'elle réussit. Son efficacité n'est limitée que par son habileté, ce qui la rend très dépendante de ses propres performances."),
                new Valorant("Astra", "Controller", new ListeAg(), "Ghana", new Ultime(7, "Lorsque Division cosmique est chargée, utilisez le TIR SECONDAIRE en forme astrale pour viser, puis le TIR PRINCIPAL pour sélectionner deux emplaements. Une division cosmique infinie connectera les deux points sélectionnés. La division cosmique bloque les balles et étouffe fortement les sons.","Division Cosmique", "/VideoSpell/Astra/AX.png"), new Signature(150, 4, 25, "ACTIVEZ pour entrer en forme astrale, ce qui vous permet de placer des étoiles avec le TIR PRINCIPAL. Vous pouvez ensuite réactiver ces étoiles pour les transformer en impulsion nova, nébuleuse ou puits de gravité.", 0, "Null", "Forme Astrale", "/VideoSpell/Astra/AX.png"), new Capacite(0, 1, 1.25, "ACTIVEZ une étoile pour faire exploser une impulsion nova. L’impulsion nova se charge brièvement avant d’exploser, désorientant tous les joueurs dans son rayon d’effet.", "Impulsion Nova", "/VideoSpell/Astra/AA.png"), new Capacite(0, 2, 14.25, "ACTIVEZ une étoile pour la transformer en nébuleuse (fumigène).UTILISEZ(F) une étoile pour la dissiper, ce qui vous permettra d’en placer une autre à un autre endroit après un délai.La dissipation forme brièvement une fausse nébuleuse à l’emplacement de l’étoile.", "Nébuleuse", "/VideoSpell/Astra/AE.png"), new Passif("null", "Null"), "VideoSpell/Astra/astra.jpg", "/VideoSpell/Astra/ghana.png", "L'agent ghanéen Astra canalise les énergies du cosmos pour façonner le champ de bataille à sa convenance. Avec une maîtrise complète de sa forme astrale et un talent pour la planification stratégique, elle a toujours une large avance sur ses ennemis."),
                new Valorant("Brimstone","Controller",new ListeAg(),"United States",new Ultime(7,"Brimstone affiche la carte aux alentours. TIREZ pour lancer une frappe orbitale à l’endroit ciblé sur la carte, infligeant énormément de dégâts aux ennemis dans la zone. Avant de tomber, la zone ciblée par Brimstone est visible par les ennemis, ce qui leur permet de s’échapper.","Rayon Orbital","/VideoSpell/Brim/BX.png"),new Signature(100,2,19.25,"Brimstone affiche la carte aux alentours. TIREZ pour marquer jusqu’à trois endroits sur la carte. TIR ALTERNATIF pour faire tomber du ciel des grenades fumigènes qui créent un nuage impactant la vision.",0,"Null","Frappe Fumigène","/VideoSpell/Brim/BE.png"),new Capacite(250,1,7,"Brimstone s’équipe d’un lance-grenade incendiaire. TIREZ pour lancer une grenade qui explose dès qu’elle touche le sol, créant une large zone enflammée blessant tous les joueurs qui se tiennent dessus.","Bombe Incendiaire","/VideoSpell/Brim/BA.png"),new Capacite(200,1,12,"Brimstone jette INSTANTANÉMENT une balise au sol, créant une large zone augmentant la cadence de tir et la vitesse de déplacement de tous les joueurs se tenant à l’intérieur.","Balise Stimulante","/VideoSpeLl/Brim/BC.png"),new Passif("Null","Null"),"/VideoSpell/Brim/Brim.jpeg","/USA.jpg","Tout droit venu des États-Unis d'Amérique, Brimstone possède un arsenal orbital qui permet à son escouade de toujours avoir l'avantage. La précision et la portée de ses compétences utilitaires font de lui un commandant sans égal sur le terrain."),
                new Valorant("Omen","Controller",new ListeAg(),"Earth",new Ultime(7,"Omen ouvre la carte devant lui et peut sélectionner un point de téléportation. TIREZ pour vous téléporter sur le point ciblé après une courte canalisation. Les adversaires peuvent empêcher votre téléportation en détruisant votre ombre avant la fin de la canalisation. APPUYEZ sur EQUIPER pour annuler l’utilisation de l’ultime.","Depuis les Ombres","/VideoSpell/Omen/OX.png"),new Signature(150,2,15,"Omen entre dans un monde parallèle et s’équipe d’un orbe d’ombre à placer sur la carte. La portée peut être ajustée via un indicateur. TIREZ pour faire apparaître un nuage de fumée à l’endroit où se trouve l’indicateur, qui bloque la vision de vos adversaires. MAINTENEZ le tir secondaire pour éloigner le marqueur et MAINTENEZ la touche du skill pour le rapprocher. APPUYEZ sur RECHARGER pour repasser en vue normale.",30,"Secondes","Voile Sombre","/VideoSpell/Omen/OE.png"),new Capacite(300,1,2,"Omen lance instantanément un projectile d’ombre qui passe à travers les murs sur une ligne droite. Tous les joueurs touchés par cette capacité voient leur distance de vision réduite à un mètre.","Paranoïa","/VideoSpell/Omen/OA.png"),new Capacite(100,2,100,"Omen se prépare à se téléporter. TIREZ pour qu’Omen se téléporte sous votre viseur après une brève canalisation. La téléportation ne laisse aucune trace sur votre passage. En revanche, vous faites un bruit caractéristique lorsque vous apparaissez, ce qui peut alerter les ennemis.","Voie des Ombres","/VideoSpell/Omen/OA.png"),new Passif("Null","Null"),"VideoSpell/Omen/Omen.jpg","Null","Redoutable contrôleur, Omen se complaît dans les ténèbres. Il manipule les ombres et peut ainsi grandement réduire la vision de ses ennemis ou encore s’enfuir en se téléportant. Sa capacité à se déplacer sur la carte n’a pas d’égal dans Valorant. Autant dire que cela sème rapidement le trouble et la peur chez ses adversaires."),
                new Valorant("Viper","Controller",new ListeAg(),"United States",new Ultime(7,"Viper s’équipe d’un diffuseur chimique. TIREZ pour créer un large nuage de poison tout autour de Viper, réduisant la visibilité et blessant tous les adversaires se tenant à l’intérieur. Le nuage ne se dissipe pas tant que Viper reste à l’intérieur.Les unités récupèrent petit à petit leurs points de vie quand elles sortent du poison.","Nid de Vipères","/VideoSpell/Viper/VX.png"),new Signature(0,1,8,"Viper s’équipe d’un lance-diffuseur de gaz qui traverse les obstacles. TIREZ pour déployer des émetteurs sur une longue ligne face à Viper. RELANCEZ la capacité pour que l’émetteur crée un mur de poison, impactant la visibilité et blessant les adversaires le traversant. Les unités récupèrent petit à petit leurs points de vie quand elles sortent du poison.",0,"Null","Écran Toxique","/VideoSpell/Viper/VE.png"),new Capacite(200,1,8,"Viper s’équipe d’un émetteur de gaz. TIREZ pour jeter l’émetteur. RELANCEZ la capacité pour que l’émetteur crée un grand nuage de poison, impactant la visibilité et blessant les adversaires se tenant à l’intérieur. L’émetteur reste en place pour l’intégralité du round, mais peut être ramassé pour être utilisé à nouveau. Les unités récupèrent petit à petit leurs points de vie quand elles sortent du poison.","Nuage de Poison","/VideoSpell/Viper/VA.png"),new Capacite(200,2,5.5,"Viper s’équipe d’un lance-grenade chimique. Viper lance une capsule de poison qui se brise lorsqu’elle touche le sol, créant une flaque qui blesse tous les adversaires se tenant dessus et leur inflige l’altération d’état Fragile. Les unités récupèrent petit à petit leurs points de vie quand elles sortent du poison.","Morsure de Serpent","/VideoSpeLl/Viper/VC.png"),new Passif("Les capacités qui appliquent la toxine font que les ennemis affectés voient instantanément leur santé maximale décroître, ce qui diminue plus ils restent longtemps dans la zone d'effet de la capacité.","Toxine"),"VideoSpell/Viper/Viper.jpeg","/USA.jpg","L’Agent Viper fait partie des contrôleurs de Valorant. Grâce à ses capacités, elle peut affecter l’environnement en créant des zones dangereuses qui handicapent l’équipe ennemie, en affectant leur mouvement ou leur visibilité. Poisons et toxines sont donc ses armes de prédilection, et elle sera une alliée de choix pour contrôler le terrain et amener son équipe vers la victoire."),
                new Valorant("Breach","initiator", new ListeAg(),"Sweden",new Ultime(7,"Breach s’équipe d’une charge sismique. TIREZ pour créer une onde de choc dans un large cône face à Breach, ralentissant et blessant les adversaires sur son passage. Cette capacité passe à travers les murs.","Onde Sismique","/VideoSpell/Breach/BX.png"),new Signature(0,1,40,"Breach s’équipe d’une charge sismique. MAINTENEZ votre tir pour augmenter la distance du tir. RELÂCHEZ pour créer une onde sismique, réduisant le champ de vision et la vitesse des adversaires touchés dans une large zone face à Breach. Cette capacité passe à travers les murs et obstacles.",40,"Secondes","Ligne de Fracture","/VideoSpell/Breach/BE.png"),new Capacite(250,2,2,"Breach s’équipe d’une charge aveuglante. TIREZ pour lancer un projectile qui traverse un mur de part en part et aveugle les ennemis à la sortie.","Point d’Ignition","/VideoSpell/Breach/BA.png"),new Capacite(200,1,2.2,"Breach s’équipe d’une charge de fusion. TIREZ pour lancer un projectile qui traverse un mur de part en part et explose à la sortie.","Réplique","/VideoSpell/Breach/BE.png"),new Passif("Null","Null"),"/VideoSpell/Breach/breach.jpg","/VideoSpell/Breach/suede.png","Initateur qui en impose, Breach est capable de faire de lourds dégâts. Mais ce n’est pas là son seul atout : il peut grandement limiter la vision des ennemis via deux de ses compétences. Il ne fait pas dans la finesse, et son kit est très complémentaire. Vous l’aurez compris, cela fait de Breach un Agent de choix sur Valorant."),
                new Valorant("Fade", "Initiator",new ListeAg(),"Turkey",new Ultime(7,"ÉQUIPEZ-vous du pouvoir de la peur. TIREZ pour envoyer une vague d'énergie cauchemardesque qui peut traverser les murs. L'énergie crée une piste vers l'ennemi, en plus de l'assourdir et de désagréger ses PV.","NUIT TOMBANTE","/VideoSpell/Fade/FX.png"),new Signature(0,1,12,"Équipez-vous d'une entité cauchemardesque. TIREZ pour lancer l'orbe. Celui-ci tombe au sol après un temps défini, et se transforme alors en entité cauchemardesque qui révèle les ennemis dans son champ de vision. Les ennemis peuvent détruire cette entité. RÉUTILISEZ la compétence pour faire tomber le projectile plus tôt.",40,"Secondes","HANTEUR","/VideoSpell/Fade/FE.png"),new Capacite(200,2,4.5,"Équipez-vous d'un orbe d'encre cauchemardesque. TIREZ pour lancer l'orbe. Celui-ci tombe au sol après un temps défini, ce qui fait exploser l'encre et crée une zone. Les ennemis pris dans cette zone ne peuvent pas en sortir par des moyens normaux. RÉUTILISEZ la compétence pour faire tomber le projectile plus tôt.","CAPTURE","/VideoSpell/Fade/FA.png"),new Capacite(250,2,3,"ÉQUIPEZ-vous d'un Rôdeur. TIREZ pour envoyer le Rôdeur sur une ligne droite. Le Rôdeur se verrouille sur les ennemis ou les pistes qui entrent dans son cône de vision frontal et les suit ; s'il atteint un ennemi, il le rend myope. MAINTENEZ la touche de TIR pour guider le Rôdeur dans la direction de votre réticule","Rodeur","/VideoSpeLl/Fade/FC.png"),new Passif("null","Null"),"/VideoSpell/Fade/fade.jpg","/VideoSpell/Fade/turquie.webp","Originaire de Turquie, la chasseuse de primes Fade utilise le pouvoir des cauchemars pour s\'emparer des secrets ennemis. Elle traque ses cibles et révèle leurs plus grandes peurs pour mieux les briser dans l\'obscurité.")
            });
        }
    }
}
